# -*- coding: utf-8 -*-
"""final_deployment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1obGJKQWPoog8zMmvr0dNnHyifciB2zE5
"""

import streamlit as st
import tensorflow as tf

@st.cache(allow_output_mutation=True)
def load_model():
  model=tf.keras.models.load_model('final_model.hdf5')
  return model
model=load_model()
st.write("""
# Chihuahua vs Muffin Classification"""
)
file=st.file_uploader("Choose a chihuahua or muffin photo from computer",type=["jpg","png"])
import cv2
from PIL import Image,ImageOps
import numpy as np
def import_and_predict(image_data,model):
    size=(224,224)
    image=ImageOps.fit(image_data,size,Image.ANTIALIAS)
    img=np.asarray(image)
    img_reshape=img[np.newaxis,...]
    prediction=model.predict(img_reshape)
    return prediction
if file is None:
    st.text("Please upload an image file")
else:
    image=Image.open(file)
    st.image(image,use_column_width=True)
    prediction=import_and_predict(image,model)
    class_names=['chihuahua', 'muffin']
    string="OUTPUT : "+class_names[np.argmax(prediction)]
    st.success(string)
